### ISSUE TITLE
Asset aggregation deprecations and additions, hook_js_alter()/hook_css_alter() changes

### ISSUE THREAD

**Issue by eneus** [skilld-labs/skilld-docker-nginx#29] opened 2023-08-31 22:08 UTC
Accoding to https://www.drupal.org/node/2888767 need cahnge default.conf:
Before:
```
        location ~* /files/styles/ {
            access_log off;
            expires 1y;
            try_files $uri @drupal;
        }
```
after:
```
        # Passes image style and asset generation to PHP.
        location ~ ^/sites/.*/files/(css|js|styles)/ {
            access_log off;
            expires 1y;
            try_files $uri @drupal;
        }
```

**Comment by andypost** [comment] 2023-08-31 22:25
Duplicate of https://github.com/skilld-labs/skilld-docker-nginx/issues/27

**Closed as completed by andypost** 2023-08-31 22:25 UTC
